// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jrhjzevapgsbvurzimov.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpyaGp6ZXZhcGdzYnZ1cnppbW92Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1NDc2NDMsImV4cCI6MjA1OTEyMzY0M30.E4aPyY-tYxvYMgeqFucJEs-9rTWw_dbaRuaqhbYq0Rg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);